#!/usr/bin/env python3
"""Generate pkg_hints.h: a name -> package table scanned from packages/*.cz
top-level lets, so "undefined name 'minimize'" can teach load("packages/
optim.cz"). Generated (never hand-edited); --check wired into make test."""
import glob, re, sys

pairs = []
seen = set()
for f in sorted(glob.glob("packages/*.cz")):
    for m in re.finditer(r"^let\s+([^\s=]+)\s*=", open(f).read(), re.M):
        name = m.group(1)
        if name not in seen:
            seen.add(name)
            pairs.append((name, f))

out = ["/* pkg_hints.h — GENERATED by tools/gen_pkg_hints.py; do not edit.",
       " * Maps every package's top-level name to its file, so the",
       " * undefined-name error can teach the load line. */",
       "static const struct { const char *name, *pkg; } pkg_hints[] = {"]
for n, f in pairs:
    out.append(f'    {{ "{n}", "{f}" }},')
out.append("};")
text = "\n".join(out) + "\n"

if "--check" in sys.argv:
    try:
        cur = open("pkg_hints.h").read()
    except FileNotFoundError:
        cur = ""
    if cur != text:
        print("pkg_hints: STALE — run tools/gen_pkg_hints.py"); sys.exit(1)
    print(f"pkg_hints: current ({len(pairs)} names)"); sys.exit(0)
open("pkg_hints.h", "w").write(text)
print(f"pkg_hints.h: {len(pairs)} names from {len(glob.glob('packages/*.cz'))} packages")
