#!/usr/bin/env python3
"""doc/builtins.tsv -> doc_table.inc. THE one escaper: the doc table's text
lives as plain tab-separated data (charter fix-from-day-one: the escaping
bug class dies here); this generator produces the C initializer rows. --check
wired into make test."""
import sys

def cesc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\\\\n', '\\n')

rows = []
for line in open('doc/builtins.tsv'):
    if line.startswith('#') or not line.strip():
        continue
    parts = line.rstrip('\n').split('\t')
    assert len(parts) == 5, parts
    rows.append('    { ' + ', '.join(f'"{cesc(p)}"' for p in parts) + ' },')
text = ("/* doc_table.inc — GENERATED by tools/gen_doc_table.py from doc/builtins.tsv;\n"
        " * do not edit. One source, one escaper, many readers. */\n" + "\n".join(rows) + "\n")
if "--check" in sys.argv:
    try: cur = open('doc_table.inc').read()
    except FileNotFoundError: cur = ""
    if cur != text:
        print("doc table: STALE — run tools/gen_doc_table.py"); sys.exit(1)
    print(f"doc table: current ({len(rows)} rows from doc/builtins.tsv)"); sys.exit(0)
open('doc_table.inc', 'w').write(text)
print(f"doc_table.inc: {len(rows)} rows")
