% demo.nu — the Neutrino tour, rebuilt on eval (v2.24.0).
%
%     neutrino> load("packages/demo.nu")
%
% Single-source honesty: every demonstration below is ONE string,
% printed as the caption and executed by eval — what you read is,
% byte for byte, what runs. Drift between the shown code and the
% real code is impossible by construction.
%
% The tour is deliberate: pause() waits for Enter after each feature.
% Piped or under make test, stdin's EOF drains the pauses instantly,
% so the same file is an interactive tour and a batch self-test.

let praw = fn t -> print(strrep(strrep(t, "{", "{{"), "}", "}}"))
let dm = fn src -> (praw("    " + src); praw("      => " + str(eval(src))); null)
let df = fn src -> (praw("    " + src); eval(src); null)
let wait = fn -> pause("\n        [ Enter to continue ] ")

print("")
print("  ╭─╴   ╶─╮   N E U T R I N O — the tour")
print("    ▪ ◉ ▪     a small functional array language")
print("  ╰─╴   ╶─╯   (every caption below is the exact code that runs)")
print("")
print("── Act I. Executable mathematics ─────────────────────────────")
print("")
print("  Euler's Basel problem, in Euler's notation:")
dm("(sum[k = 1:n] 1/k^2) where n = 100000")
print("      (pi^2/6 = " + str(pi ^ 2 / 6) + ")")
wait()
print("  The Gaussian integral, squared — pi by the polar miracle:")
dm("(2 * integral(fn u -> exp(-u^2), 0, 10)) ^ 2")
wait()
print("── Act II. The blackboard's word order ───────────────────────")
print("")
print("  State the formula first, the constants after — 'where':")
dm("(-b + [-d, d]) / (2*a) where a = 1, b = -3, c = 2, d = sqrt(b^2 - 4*a*c)")
wait()
print("  A mask's mean is its frequency — the one-line statistic:")
dm("rng(2); mean(-1.96 < z < 1.96) where z = randn(1, 10000)")
print("      (theory: 0.95)")
wait()
print("── Act III. Functions as values ──────────────────────────────")
print("")
print("  Anonymous, applied on the spot:")
dm("(fn x -> x^2 + 1)(3)")
wait()
print("  Recursion — Euclid's algorithm, twenty-three centuries old:")
df("let gcd_ = fn a, b -> if b == 0 then a else gcd_(b, mod(a, b)) end")
dm("gcd_(1071, 462)")
wait()
print("  Compose any function with itself n times — and find a legend:")
df("let iterate = fn f, n -> if n <= 0 then (fn x -> x) else (fn x -> f(iterate(f, n-1)(x))) end")
dm("iterate(fn t -> sqrt(1 + t), 40)(1)")
print("      (the golden ratio: the fixed point of sqrt(1+x))")
wait()
print("── Act IV. Pipelines — the oscillation and the fan-out ───────")
print("")
print("  Values flavor-change down the pipe: element-wise through ~>,")
print("  whole through |>, and back again:")
dm("1:12 ~> (@ ^ 2) |> (fn v -> v[v > 50]) ~> sqrt |> mean")
wait()
print("  Fan-out: one value, a whole dashboard — crown jewel #2:")
dm("rng(7); rand(1, 500) |> {mu = mean, sd = std, hi = max, lo = min}")
wait()
print("  The birthday problem, solved in one sentence:")
dm("1:m ~> (fn k -> prod[j = 1:k] (1 - (j-1)/365)) |> (fn p -> find(p < 0.5)[1]) where m = 60")
print("      (people needed for even odds of a shared birthday)")
wait()
print("  Fan-out thesis line: one matrix, many measurements:")
dm("rng(1); A |> {a = det, b = inv} where A = eig(rand(2)).vectors")
wait()
print("── Act V. The calculus ───────────────────────────────────────")
print("")
load("packages/symb.nu")
print("  Symbolic differentiation, string in, string out (symb.nu):")
dm("deriv(\"sin(x)/x\")")
wait()
print("  The symbolic derivative is a function; fzero hunts its root:")
dm("fzero(dfun(\"sin(x)/x\"), 4, 5)")
print("      (the tan x = x critical point)")
wait()
print("── Act VI. Money ─────────────────────────────────────────────")
print("")
load("packages/finance.nu")
print("  The 30-year mortgage, HP-12C style (finance.nu):")
dm("format(\"fixed\", 2); pmt(360, 0.0575/12, 340000, 0)")
print("      (per month; note fixed-decimals mode for money)")
df("format(\"default\")")
wait()
print("── Finale. Pictures ──────────────────────────────────────────")
print("")
print("  A damped wave and a seeded scatter (see the Plots tab in the")
print("  browser; gnuplot or ascii at a terminal):")
plot(0:0.1:12, exp(-(0:0.1:12) / 6) .* sin(0:0.1:12), {title = "exp(-x/6) sin(x)"})
rng(4)
load("packages/scatter.nu")
scatter_titled(rand(1, 40), 2 * rand(1, 40) + randn(1, 40) * 0.2, "seeded scatter")
print("")
print("  Tour complete. 159 builtins, 9 packages, 3 machine-verified")
print("  books — MANUAL.md, PACKAGES.md, BOOK.md. The syntax is frozen;")
print("  what you just read is what it ran, byte for byte.")
print("")
